// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDKSdmdSZN8InZsnfFShk5zBLwZuMRQZg',
    appId: '1:274927672089:web:5b925eed83098d30a34388',
    messagingSenderId: '274927672089',
    projectId: 'oxygen-mart-2023',
    authDomain: 'oxygen-mart-2023.firebaseapp.com',
    storageBucket: 'oxygen-mart-2023.firebasestorage.app',
    measurementId: 'G-ZNEN54L6LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzBaKCph0f5AtEtw3ezrhF2IRyO0ch2CM',
    appId: '1:274927672089:android:10890c5647dd5a58a34388',
    messagingSenderId: '274927672089',
    projectId: 'oxygen-mart-2023',
    storageBucket: 'oxygen-mart-2023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHzNYKDWmxFUcNsoE-LN-3mPsXx0__yU',
    appId: '1:274927672089:ios:4f11de62e4a9a770a34388',
    messagingSenderId: '274927672089',
    projectId: 'oxygen-mart-2023',
    storageBucket: 'oxygen-mart-2023.firebasestorage.app',
    iosClientId: '274927672089-teljkbn8phg9kfgfr7rfj2jrn7acst23.apps.googleusercontent.com',
    iosBundleId: 'com.OxygenDeliveryApp',
  );

}